language: go
sudo: false
go:
  - tip
script:
  - go test -v -cover -race -coverprofile=coverage.out
after_script:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci
